### ISSUE TITLE
Color Scheme Options

### ISSUE THREAD

**Issue by wpalchemist** [wpalchemist/pressable-trial#2]
Here are two color scheme options.  Which do you prefer?  Keep in mind that the site is going to be a modified version of this theme: https://wordpress.org/themes/dara/  That means that colors are going to primarily be used for contrast and highlighting instead of dominating the screen like they do on your current site.  If you don't like either of these, or would like to see a mockup of the site in these colors, let me know.

![5c3902-9be564-85cb33-0072bb-f7b32b](https://user-images.githubusercontent.com/16658165/38582445-99c6cfb2-3cc4-11e8-8bd7-a32f7cefc41a.png)
![5c3902-1b2f33-28502e-7ea172-efcb68](https://user-images.githubusercontent.com/16658165/38582446-99e062c4-3cc4-11e8-8fa9-4d3ac2769c41.png)

**Comment by threegreenbirds** [comment]
We like the second one, but it would be great to see a screenshot of what it will look like.

Can we change this later? We've been hearing good things about red lately but we're not ready to go there yet.

**Comment by wpalchemist** [comment]
I'll send a screenshot with the second color scheme soon!

**Comment by wpalchemist** [comment]
@threegreenbirds  Here's a screenshot of how the site looks with the second color scheme, and with the logo in that color scheme.  I'm still working out some details of the page layout, so this isn't the final look for the homepage, but it should give you an idea of where I am going with the color scheme.  What do you think?  Do you want to stick with this, or see it with the other colors?

![image](https://user-images.githubusercontent.com/16658165/38643082-dd3bbfc4-3d90-11e8-9e4f-6c22b64c8a44.png)

**Comment by threegreenbirds** [comment]
We like it! Let's proceed.
