### ISSUE TITLE
Social Media Links

### ISSUE THREAD

**Issue by wpalchemist** [wpalchemist/pressable-trial#4]
Could you give me the URLs of the social media profiles you want the site to link to?

**Comment by threegreenbirds** [comment]
https://www.facebook.com/ThreeGreenBirds
https://twitter.com/ThreeGreenBirds
https://www.instagram.com/ThreeGreenBirds
https://www.youtube.com/user/ThreeGreenBirds

We are also considering opening a Snapchat account - do you think that would help us reach younger people?

**Comment by wpalchemist** [comment]
@threegreenbirds Thanks for the social media links!

Unless you have someone in your organization who is Snapchat-savvy, I recommend against using Snapchat.  It might be a great way to reach a different audience, but only if you have the time and energy to do it right.  Finding the time to maintain social media accounts is always tough for volunteer-run organizations, and you probably have better ways to spend your time.  With social media, I generally think it is better to not use it at all than to use it poorly.  Having said all of that, if you do have someone in your organization who is a great Snapchatter and has the time and energy for it, then by all means take advantage of that.

**Comment by threegreenbirds** [comment]
Okay, let's skip Snapchat for now.
