### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by wpalchemist** [wpalchemist/pressable-trial#5]
What fields would you like on the contact form?  I'm thinking you probably want Name, Email, Location, and Message.  Anything else?  

When the contact form is submitted, who should get notifications?  Do you want to set up location-based locations so that if someone enters a city where there is a local chapter, the local chapter will get the notification?

**Comment by threegreenbirds** [comment]
It would be nice to have some way for them to indicate what they're contact us about - general questions, how to get involved, donations, people wanting to start a new chapter, sharing stories, etc. What's a good way to do that?

You can have the notifications go to chris.hardie+threegreenbirds@automattic.com. I don't think we need to do the local notifications for now but that's a cool idea to think about for the future.

**Comment by wpalchemist** [comment]
@threegreenbirds Sounds good!  I'll add a checkbox field where they can select the reason for contacting you.
