### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by wpalchemist** [wpalchemist/pressable-trial#6]
I'll get donations set up with PayPal.  Are you open to using other payment gateways, or do you only want to use PayPal?

Would you like users to have the option to set up a recurring donation instead of just a one-time donation?

**Comment by threegreenbirds** [comment]
We're open to using other options as long as it's not confusing for users. What are the pros/cons of PayPal versus others you recommend?

Recurring donations would be awesome!!!

**Comment by wpalchemist** [comment]
I'm going to recommend that you accept credit cards through the Stripe payment gateway instead of using PayPal.  There are several reasons for this:
- Not everyone has a PayPal account, and some people don't like using PayPal
- Stripe has similar payment fees to PayPal, and setting up an account with them is free
- Stripe automatically deposits money into your bank account

But the biggest reason I recommend using Stripe is that it is the payment gateway supported by GiveWP: https://givewp.com/

This is a very well-known, well-made, and well-supported plugin.  It uses the Stripe payment gateway to accept credit cards. GiveWP is nice because it makes things really easy and intuitive for you and your customers, and it gives you lots of thorough reports.  I am confident that this would be worry-free for you and require very little maintenance, and if you run into problems, their support is excellent.  If you want recurring payments with GiveWP, you will have to purchase an extension for $197/year.  You can go ahead and buy that now and set it up, or you might want to wait a few months to see what volume of donations you get on the new site to see if it is worth the extra cost for recurring donations.

There are a few plugins out there that let you do recurring payments with PayPal (such as Charitable https://wordpress.org/plugins/charitable/) but they are all complicated for you to set up, or are not well-maintained, and none of them have the good reporting that GiveWP has.  You would still have to pay for recurring donations.

If GiveWP sounds like a good option to you, I'll get that set up.  If you want more information about alternatives, let me know.

**Comment by threegreenbirds** [comment]
Going with Stripe and GiveWP sounds good to us.

**Comment by wpalchemist** [comment]
@threegreenbirds Great!  I think you're going to be really happy with GiveWP.  I'll get the basic version set up for you now, and later we can discuss whether you'd like to add the Recurring Donations add-on.
