### ISSUE TITLE
Events Page

### ISSUE THREAD

**Issue by wpalchemist** [wpalchemist/pressable-trial#7]
On your "Events & Programs" page, would you like to integrate with meetup.com to display an events calendar or events list?  We could automatically pull data in from meetup.com, so you wouldn't have to do much work to maintain the events calendar - you would just need to maintain a list of chapter accounts.

**Comment by threegreenbirds** [comment]
That sounds like a great idea, but right now we only have one Meetup that's really active. For now could we just do astatic list of events/programs and come back to that later? Maybe we can include a link for folks who want to sign up new Meetup chapters?

**Comment by wpalchemist** [comment]
@threegreenbirds In that case, it sounds like what you have on the page now is probably the best thing to do for now, but down the road as you get more meetup groups, you might want to link to all of those groups, or pull meetup data in from meetup.com.
